BungieRootPath = "https://www.bungie.net"
BungieAPIRootPath = "https://www.bungie.net/Platform"
GetManifestEndpoint = "/Destiny2/Manifest/"
DestinationFolderPath = "C:\\Users\\wesle\\Repos\\guardians-central"
ManifestZipPath = "C:\\Users\\wesle\\Repos\\guardians-central\\Sqlite3Destiny2DB.zip"
ExtractionPath = "C:\\Users\\wesle\\Repos\\guardians-central\\Extractions"
